### PR TITLE
Update Jenkinsfile with artifact dir

### PR DESCRIPTION
**Pull request by josephworks**

### CODE REVIEW

**Comment by GMatrixGames** [comment]
The actual directory is build/localCache/*

**Comment by josephworks** [comment]
Hey, what happened with Jenkins pr build

**Comment by josephworks** [comment]
Oh ok

**Comment by josephworks** [comment]
Can you fix that, I am at school

**Comment by GMatrixGames** [comment]
Already did

**Comment by josephworks** [comment]
Ok thanks

**Pull request merged**
