### PR TITLE
Fixed issue with dual stages

### PR DESCRIPTION
**Pull request by josephworks**

### CODE REVIEW

**Comment by josephworks** [comment]
It’s cause I accidentally added stages {} twice.

**Comment by josephworks** [comment]
Please merge so I can build

**Comment by josephworks** [comment]
And why is the pull requests not building in jenkins

**Comment by josephworks** [comment]
i will try and restart the jenkins server

**Comment by GMatrixGames** [comment]
I don't know tbh

**Comment by josephworks** [comment]
Go to http://josephworks.ddns.net:8080/restart

**Comment by josephworks** [comment]
Hopefully that fixes it

**Pull request merged**
